config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin/manage', as: 'rails_admin'

  namespace :admin do
    root to: 'forms#index'
    resources :forms
  end

  namespace :api do
    namespace :v1 do
      resources :form_submissions
      resources :forms, shallow: true, except: %i[new edit] do
        resources :sections, except: %i[new edit] do
          resources :questions, except: %i[new create edit] do
            resources :choices, except: %i[new create edit]
          end
        end
      end
    end
  end
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::AdminController
  before_action :set_admin_form, only: [:show, :edit, :update, :destroy]

  # GET /admin/forms
  # GET /admin/forms.json
  def index
    @forms = Form.all
  end

  # GET /admin/forms/1
  # GET /admin/forms/1.json
  def show
  end

  # GET /admin/forms/new
  def new
    @form = Form.new
  end

  # GET /admin/forms/1/edit
  def edit
  end

  # POST /admin/forms
  # POST /admin/forms.json
  def create
    @form = Form.new(admin_form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to [:admin, @form], notice: 'Form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/forms/1
  # PATCH/PUT /admin/forms/1.json
  def update
    respond_to do |format|
      if @form.update(admin_form_params)
        format.html { redirect_to [:admin, @form], notice: 'Form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/forms/1
  # DELETE /admin/forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to admin_forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_form
      @form = Form.find(params[:form_id] || params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_form_params
      params.require(:form).permit(:name, :description, :completion_content,
        sections_attributes: [
          :id, :form_id, :name, :content, :order, :_destroy,
          questions_attributes: [
            :id, :label, :content, :required, :order, :question_type,
            :validate_as, :placeholder, :section_id, :_destroy,
            choices_attributes: [
              :id, :question_id, :question_dependency_id, :metadata,
              :maximum_chosen, :label, :order, :_destroy
            ],
            question_dependency_attributes: [
              :id, :question_id, :display, :and, :_destroy
            ]
          ]
        ]
      )
    end
end

app/controllers/api/v1/forms_controller.rb
# frozen_string_literal: true

class Api::V1::FormsController < Api::V1::ApiController
  before_action :find_form, only: %i[show destroy]
  before_action :can_create_form, only: :create

  def index
    @forms = @application.forms.all
    render json: @forms
  end

  def show
    render json: @form
  end

  def create
    @form = @application.forms.find_or_initialize_by(id: form_params[:id])
    if !@form.persisted?
      @form = @application.forms.new(form_params)
      render_create
    else
      render_update
    end
  end

  private def render_create
    if @form.save
      render json: @form, status: :created
    else
      render json: @form.errors, status: :unprocessable_entity
    end
  end

  private def render_update
    if @form.update_attributes(form_params)
      render json: @form, status: :ok
    else
      render json: @form.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @form.destroy
      render json: :no_content, status: :no_content
    else
      render json: @form.errors, status: :unprocessable_entity
    end
  end

  private

  def find_form
    @form = Form.find(params[:id])
  end

  def form_params
    make_form_params
  end

  private def make_form_params
    # This make a standard for our form_params.
    # Here we are passing the correct parameter to work with nested_params and
    # we are permitting it to be used.
    permitted = params
                .require(:form)
                .permit(:id, :uuid, :completion_content, :application_id,
                        sections: [:id, :uuid, :form_id, :name, :order, :content, :_destroy,
                                   questions: [:id, :uuid, :key, :label, :content, :order, :hidden,
                                               :question_type, :validate_as, :section_id, :required,
                                               :placeholder, :_destroy,
                                               question_dependency: [
                                                 :id,
                                                 :and,
                                                 :display,
                                                 :_destroy,
                                                 :uuid,
                                                 question_dependency_choices: %i[
                                                   choice_id
                                                   id
                                                   uuid
                                                   _destroy
                                                 ]
                                               ],
                                               choices: [
                                                 :id,
                                                 :maximum_chosen,
                                                 :label,
                                                 :uuid,
                                                 :order,
                                                 :_destroy,
                                                 metadata: {}
                                               ]]])
    permitted[:sections_attributes] = permitted.delete(:sections)
    permitted[:sections_attributes].each do |section|
      section[:questions_attributes] = section.delete(:questions)
      section[:questions_attributes].each do |question|
        choices_attributes = question[:choices] ? question.delete(:choices) : []
        question[:choices_attributes] = choices_attributes
        question_dependency_attributes = question[:question_dependency] ? question.delete(:question_dependency) : nil
        next unless question_dependency_attributes
        question_dependency_choices_attributes = question_dependency_attributes[:question_dependency_choices] ? question_dependency_attributes.delete(:question_dependency_choices) : []
        question_dependency_attributes[:question_dependency_choices_attributes] = question_dependency_choices_attributes
        question[:question_dependency_attributes] = question_dependency_attributes
      end
    end
    permitted
  end

  def can_create_form
    can = Authorization.can_create_form?(@api_key)
    render json: { error: "You don't have permission for creating." }, status: 401 unless can
  end
end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/views/admin/forms/_add_question.html.haml
.card.float-left.mt-3.mb-0{ id: "#{unique_dom_id(f)}_add_question",
  class: "#{collapse ? 'collapse' : '' }" }
  .card-body.pr-4
    .card-title
      .actions.mr-0
        = link_to "##{unique_dom_id(f)}_add_question",
          class: 'btn btn-secondary btn-sm',
          data: { toggle: 'collapse' }, 'aria-expanded': 'false',
          'aria-controls': "#{unique_dom_id(f)}_add_question" do
          = icon 'fas', 'times'
    .row
      - ['string', 'text', 'content', 'boolean', 'address', 'select',
        'checkboxes', 'radio', 'multiselect'].each do |type|
        .col-lg-3.col-md-4.pt-4{ id: "#{unique_dom_id(f)}_question_#{type}" }
          = render 'question_type', f: f, type: type,
            association: association, dependency_enabled: dependency_enabled,
            selector: selector, insert_method: insert_method

app/views/admin/forms/_choice_fields.html.haml
.choice.nested-fields{ id: f.object.sortable_id,
  data: { 'dom-id': "#{unique_dom_id(f)}" } }
  = f.input_field :id, as: 'hidden'
  .input-group.mb-3
    .input-group-prepend
      .btn.text-muted.bg-white.handle
        = icon 'fas', 'grip-horizontal'
    = f.input_field :label, class: 'form-control'
    .input-group-append
      = link_to_remove_association f, { title: 'delete',
        class: 'btn text-muted bg-white' } do
        = icon 'fas', 'times'
      - if dependency_enabled
        = link_to_add_association 'Add Dependency', f.options[:parent_builder],
          :question_dependency, title: 'Add Dependency',
          class: 'btn btn-primary text-white',
          data: { 'association-insertion-node': "[data-dom-id='#{unique_dom_id(f)}']",
          'association-insertion-method': 'after' },
          disabled: f.object.question_dependency_id.present?,
          render_options: { locals: { dependency_enabled: dependency_enabled }}
  .question_dependency_container

app/views/admin/forms/_form.html.haml
= minimal_form_for [:admin, @form] do |f|
  - if @form.errors.any?
    #error_explanation
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this admin_form from being saved:"
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message

  = f.input :name
  = f.input :description
  %h4 Sections
  .sortable#sections
    - f.object.sections.order(:order).each.with_index do |section,index|
      = f.simple_fields_for :sections, section do |fs|
        = render 'section_fields', f: fs, dependency_enabled: true

  %h4 Completion Message
  = f.input :completion_content

  .actions
    = f.submit 'Save Form', class: 'btn btn-block btn-primary'

app/views/admin/forms/_question_dependency_fields.html.haml
.question_dependency{ id: "#{unique_dom_id(f)}" }
  = f.input_field :id, as: 'hidden'
  = f.input_field :question_id, as: 'hidden'
  = render 'add_question', f: f, association: :question,
    collapse: false, dependency_enabled: false,
    selector: "##{unique_dom_id(f)}_add_question",
    insert_method: 'replaceWith'

app/views/admin/forms/_question_fields.html.haml
.card.nested-fields{ id: f.object.sortable_id }
  .card-body
    .card-title
      %h7
        = t(question_type).humanize.upcase
      = f.input_field :id, as: 'hidden'
      = f.input_field :question_type, as: 'hidden', value: question_type
      .actions
        = link_to "##{unique_dom_id(f)}_content",
          title: 'collapse', class: 'btn btn-secondary btn-sm collapsed',
          data: { toggle: 'collapse' }, 'aria-expanded': 'false',
          'aria-controls': "#{unique_dom_id(f)}_content" do
          = icon 'fas', 'minus'
        = link_to_remove_association f, { title: 'delete',
          class: 'btn btn-secondary btn-sm' } do
          = icon 'fas', 'times'
      = f.input :required
    = f.input :label, wrapper_html: { class: 'mb-0' }
    .content.collapse.mt-3{ id: "#{unique_dom_id(f)}_content" }
      = f.input :content
      - if f.object.choices_allowed?
        %h7.mb-2 CHOICES:
        .sortable{ id: "#{unique_dom_id(f)}_choices" }
          - if f.object.choices.present?
            - f.object.choices.order(:order).each.with_index do |choice,c_index|
              = f.simple_fields_for :choices, choice do |fc|
                = render 'choice_fields', f: fc,
                  dependency_enabled: dependency_enabled
        = link_to_add_association 'Add Choice', f, :choices,
          title: 'Add Choice', class: 'btn btn-primary text-white',
          data: { 'association-insertion-node': "##{unique_dom_id(f)}_choices",
          'association-insertion-method': 'append' },
          render_options: { locals: { dependency_enabled: dependency_enabled }}
    .btn.btn-link.text-muted.handle
      = icon 'fas', 'grip-horizontal', class: 'fa-2x'

app/views/admin/forms/_question_type.html.haml
= link_to_add_association f, association,
  wrap_object: Proc.new { |q| q.question_type = type; q },
  data: { 'association-insertion-node': selector,
  'association-insertion-method': insert_method }, title: t(type).humanize,
  class: 'btn btn-link btn-block border',
  render_options: { locals: { dependency_enabled: dependency_enabled,
  question_type: type }} do
  = inline_svg_tag t(type), class: 'fill-primary m-4'
  %hr.border.m-1
  .text-dark= t(type).humanize

app/views/admin/forms/_section_fields.html.haml
.card.nested-fields{ id: f.object.sortable_id }
  .card-body
    = f.input_field :id, as: 'hidden'
    .actions
      = link_to "##{unique_dom_id(f)}_content", title: 'collapse',
        class: 'btn btn-primary collapsed', data: { toggle: 'collapse' },
        'aria-expanded': 'false',
        'aria-controls': "#{unique_dom_id(f)}_content" do
        = icon 'fas', 'minus'
      = link_to_remove_association f, { title: 'delete',
        class: 'btn btn-primary' } do
        = icon 'fas', 'times'
    = f.input :name, as: :string, wrapper_html: { class: 'mb-0' }
    .content.collapse.mt-3{ id: "#{unique_dom_id(f)}_content" }
      = f.input :content
      - if f.object.questions.present?
        .sortable{ id: "#{unique_dom_id(f)}_questions" }
          - f.object.questions.order(:order).each.with_index do |question,q_index|
            = f.simple_fields_for :questions, question do |fq|
              = render 'question_fields', f: fq,
                question_type: fq.object.question_type,
                dependency_enabled: dependency_enabled
      = link_to 'Add Question', "##{unique_dom_id(f)}_add_question",
        title: 'Add Question', class: 'btn btn-primary text-white collapsed',
        data: { toggle: 'collapse' }, 'aria-expanded': 'false',
        'aria-controls': "#{unique_dom_id(f)}_add_question"
      = render 'add_question', f: f, association: :questions,
        collapse: true, dependency_enabled: dependency_enabled,
        selector: "##{unique_dom_id(f)}_questions > .card:last-of-type",
        insert_method: 'after'
    .btn.btn-link.text-white.handle
      = icon 'fas', 'grip-horizontal', class: 'fa-2x'

app/views/admin/forms/edit.html.haml
%h2.mt-3 Edit Form
%hr.my-3

= render 'form'

= link_to 'Cancel', admin_forms_path, class: 'btn btn-block btn-danger mt-3'

app/views/admin/forms/index.html.haml
.float-right= link_to 'New Form', new_admin_form_path,
  class: "btn btn-sm btn-primary mt-3 mb-2"

%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Description
      %th Updated At
      %th Created At
      %th

  %tbody
    - @forms.each do |form|
      %tr
        %th{scope: 'row'}
          = link_to form.name, admin_form_path(form), title: 'show'
        %td= form.description
        %td= form.updated_at.to_s(:long)
        %td= form.created_at.to_s(:long)
        %td.text-right
          %span.mx-1
            = link_to admin_form_path(form), title: 'show' do
              = icon 'fas', 'search'
          %span.mx-1
            = link_to edit_admin_form_path(form), title: 'edit' do
              = icon 'fas', 'edit'
          %span.mx-1
            = link_to admin_form_path(form), method: :delete, title: 'delete',
              data: { confirm: 'Are you sure?' } do
              = icon 'fas', 'times', class: 'text-danger'

app/views/admin/forms/new.html.haml
%h2 New Form

= render 'form'

= link_to 'Cancel', admin_forms_path, class: 'btn btn-block btn-danger mt-3'

app/views/admin/forms/show.html.haml
%p#notice= notice

%h3= @form.name
%p= @form.description
%p= @form.completion_content
- @form.sections.order(:order).each do |section|
  %h4
    =section.name
    %small.text-muted=section.content
  %hr
  - section.questions.order(:order).each do |question|
    %p= question.label

= link_to 'Edit', edit_admin_form_path(@form)
\|
= link_to 'Back', admin_forms_path